### ISSUE TITLE
`providedBy` does not respect `super`

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#11]
In https://bugs.launchpad.net/zope.interface/+bug/448712, Dieter Maurer reported:

> In some places, the implementation of a subclass adapter may take advantage of that defined for a base class. In such cases, "super" comes to mind. Unfortunately, "providedBy" (implicitely during in adapter lookup) does not respect "super" as shown by the folloging transscript:

```
>>> from zope.interface import Interface, implements
>>> class I1(Interface): pass
...
>>> class B(object): implements(Interface)
...
>>> class C(B): implements(I1)
...
>>> c=C()
>>> from zope.interface import providedBy
>>> list(providedBy(c))
[<InterfaceClass __main__.I1>, <InterfaceClass zope.interface.Interface>]
>>> list(providedBy(super(C,c)))
[<InterfaceClass __main__.I1>, <InterfaceClass zope.interface.Interface>]
```

**Comment by jamadden** [comment]
Here, class B has a descriptor, `ObjectSpecificationDescriptor`, in its `__providedBy__` attribute. `providedBy(o)` asks for that attribute. `ObjectSpecificationDescriptor`, in turn, asks the instance for its `__provides__` attribute.

Both `B` and `C` have a `_provides__` class attribute that is once again a descriptor.

Getting an attribute on a `super` object only works for descriptors. And instead of passing in the next class in the MRO to the object, it passes in the type of its argument. Thus, `super(C, c).__providedBy__` is exactly the same as invoking `ObjectSpecificationDescriptor.__get__(B.__providedBy__, c, C)`. And that in turn does `c.__provides__`, which is the same as `ClassProvides.__get__(C.__provides__, c, C)`. So in short, there doesn't seem to be a graceful, elegant way to detect `super` and implement something special for it.

It's still possible for `providedBy` to do something custom for `super`:

```diff
-----------------------------------------------------------------------
modified: src/zope/interface/declarations.py
-----------------------------------------------------------------------
@@ -896,7 +896,14 @@ def providedBy(ob):

     # Try to get __providedBy__
     try:
-        r = ob.__providedBy__
+        if isinstance(ob, super):
+            # Begin our search here.
+            class_that_invoked_super = ob.__thisclass__
+            mro = class_that_invoked_super.mro()
+            next_class = mro[mro.index(class_that_invoked_super) + 1]
+            r = next_class.__providedBy__.__get__(ob.__self__, next_class)
+        else:
+            r = ob.__providedBy__
     except:
         # Not set yet. Fall back to lower-level thing that computes it
         return getObjectSpecification(ob)
```

With that change the example works as desired:
```pycon
>>> list(providedBy(super(C, c)))
[<InterfaceClass zope.interface.Interface>]
```
