### ISSUE TITLE
`unregisterAdapter` uses '==' while the underlying adapter registry uses 'is'

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#12]
In https://bugs.launchpad.net/zope.interface/+bug/551049, @mgedmin reported:

> Try this:

```
class MyTestClass(PlacelessSetUp):

    def _handler(self, event):
        print "Got event!"

    def test(self):
        sm = zope.component.getGlobalSiteManager()
        sm.registerHandler(self._handler, required=(zope.interface.Interface, ))
        assert sm.unregisterHandler(self._handler, required=(zope.interface.Interface, ))
        zope.event.notify(object())
```

> The assertion will demonstrate that the global site manager thinks it successfully unregistered the adapter, yet the subsequent notify() will invoke our handler.
> 
> Why? Because self._handler creates a new bound method instance every time you write that expression. sm.unregisterHandler compares it to the previously registered factory object using '==' which returns true. But then the site manager invokes zope.interface.adapter.BaseAdapterRegistry.unsubscribe, which uses 'is' for identity checking and therefore thinks it got a different handler.
> 
> zope.component should use the same kind of check as the underlying implementation, because it now lies to the programmer about unregistering an adapter that really remains registered.

@d03cc followed up:

> Trying to reproduce it, I noticed that the code that does not do the proper unregistration is in zope.interface and not in zope.component

**Comment by dwt** [comment]
At the Zope Phoenix Sprint in Halle, we just spent another two hours on this fine distinction, this time in unregisterHandler.

As far as I can see, the underlying culprit is https://github.com/zopefoundation/zope.interface/blob/master/src/zope/interface/adapter.py#L180 which should use `==` to compare the handlers.

Is there a timeline to fix this? As far as I can see using `==` here would make it easy to use instance methods for all the handlers which (to me) seems highly desirable.

To test, this, registering an instance method of a test case and trying to unregister is a good test case.
