### ISSUE TITLE
A plan for 5.0.0 release

### ISSUE THREAD

**Issue by frenzymadness** [zopefoundation/zope.interface#185]
Hello.

I see that the 5.0.0dev0 is released on PyPI. I am a packager of zope.interface in Fedora and I am curious about the next plans/schedule. What is the plan? Will there be any beta/rc release? I am asking because I want to plan in which phase will be the best to update the RPM package in Fedora.

By the way, the "Changes" page in the documentation is outdated: https://zopeinterface.readthedocs.io/en/latest/changes.html

Have a nice day.

**Comment by mgedmin** [comment]
That looks like an accident, and not an intentional release.  The only files that have been uploaded are binary manylinux wheels produced by our CI runners.

Here's the job that did the upload: https://travis-ci.org/zopefoundation/zope.interface/builds/660204326
I'm not sure why, since only tags are supposed to be uploaded, and commit https://github.com/zopefoundation/zope.interface/commit/0fc4148b8a17884f62ea013f962e156dea9229bc doesn't seem to have any tags.

@jamadden, any ideas?  It was your commit.

**Comment by mgedmin** [comment]
Back to your question: I don't think we have any specific plans. Usually people make releases when they feel there's a need for them.  E.g. I made a 4.7.2 release today in response to a bug report (#184).

**Comment by jamadden** [comment]
> @jamadden, any ideas? It was your commit.

No, none whatsoever 😕 

> By the way, the "Changes" page in the documentation is outdated:

Thanks. The RTD webhook wasn't working. I've re-synced it so hopefully we stay current from now on.

> What is the plan?

Speaking for myself, I would like to see #181, #182 and #183 merged, along with a fix for #8 and then release 5.0 (the common themes: potentially-breaking cleanups and fixes for sharp edges, plus performance improvements); hopefully that can happen this week or the next. Pre-releases have become much less useful these days, now that pip won't install them by default and PyPI doesn't show them by default so those are rarely used. Sometimes the Plone community (@jensens) uses in-development builds to run their large test suite, and that's very helpful.

**Comment by mgedmin** [comment]
I've deleted the erroneous 5.0.0.dev0 release from PyPI and added some printfs to the travis jobs so we can see what tags prompted an upload should this ever happen again.

**Comment by frenzymadness** [comment]
Thank you for the quick replies. I'll wait for the final release. Have a nice day.
