### ISSUE TITLE
how to find the zope.interface version in python?

### ISSUE THREAD

**Issue by ebonat** [zopefoundation/zope.interface#187]
how to find the zope.interface version in python?

```
- zope.interface.version
- zope.interface.__version__
```

thanks

-ernest

**Comment by jamadden** [comment]
Try pkg_resources. 

```python
pkg_resources.require('zope.interface')[0].version
```

**Comment by ebonat** [comment]
NameError: name 'pkg_resources' is not defined

What is the import?

**Comment by ebonat** [comment]
i believe in python we use:

- zope.interface.version
- zope.interface.__version__

**Comment by jamadden** [comment]
> NameError: name 'pkg_resources' is not defined
> What is the import?

Uh, `import pkg_resources`?

> i believe in python we use:

Some packages may. Many don't. (It's a pain to maintain, IMO.) `pkg_resources` [works](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#distribution-attributes) for any package installed using pip/setuptools.

**Comment by icemac** [comment]
A long time ago I documented for myself:

```python
import pkg_resources
pkg_resources.get_distribution('my.package').version
```
The result seems to be the same to the call @jamadden provided.

**Comment by icemac** [comment]
`pkg_resources` is provided by `setuptools`, I believe.

**Comment by mgedmin** [comment]
In the future we'll probably switch to using [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions), but it's only just been added to Python 3.8 as a provisional module and the API might change.

I'm leaving this comment here in case somebody googles up this issue five years from now.

**Comment by icemac** [comment]
I think the question is answered in enough detail, so I am closing the issue now.

**Comment by ebonat** [comment]
i don't see any possible update for:

```
- zope.interface.version
- zope.interface.__version__

```
why i need to use pkg_resources module to zope.interface only?

**Comment by jensens** [comment]
@ebonat I do not get the point. 

Today eggs/wheels as containers to distribute packages and the package `setuptools` are the standard way to deal with package management. 

The version number is part of the packages metadata. `pkg_resources` as part of `setuptools` is the module to read this metadata. I do not see why one would want to use the convention from former times - when using `__version__`  was a valid workaround for missing well defined metadata - today, when a supported way to deal with package metadata is in place and broadly supported.

**Comment by mgedmin** [comment]
@ebonat Why do you need to know the version of zope.interface, programatically, anyway?  What's the use case?

**Comment by jensens** [comment]
> and having setup.py extract it via some regexp magic or similar 

Vice versa is better with less headache: Define it in setup.[py|cfg] and extract it in the __init__ (otherwise you need to load code for fetching metadata on install (which you do not want)).

**Comment by jamadden** [comment]
> Vice versa is better with less headache: Define it in setup.[py|cfg] and extract it in the `__init__` (otherwise you need to load code for fetching metadata on install (which you do not want)).

The "regexp magic" @mgedmin referred to involves having setup.py read `src/zope/interface/__init__.py` as text and find the magic variable assignment. No code loading needed (beyond the basic stdlib).

I'm not quite sure I understand the vice-versa method. Unless you're suggesting that `__init__.py` should contain the call to `pkg_resources` and assign the result to a variable? Without an extremely compelling use case, I don't understand why we'd do that.

**Comment by mgedmin** [comment]
A big -1 for importing pkg_resources in `zope/interface/__init__.py` because of https://github.com/pypa/setuptools/issues/510.

(Yes, I know we import pkg_resources in our `zope/__init__.py`, but I believe that file does not get installed when you pip install zope.interface, as pip has some other, better way of supporting namespace packages.  Check it out: run `tox -e py27`, then look in .tox/py27/lib/python2.7/site-packages/zope -- no `__init__.py` there!)

(And yes, that bug might be a good argument for exposing zope.interface's version without going through pkg_resources, but (1) why is the version necessary at all, (2) if it's for debug reasons, is the slowdown important, and (3) importlib_metadata exists on PyPI and I don't think it suffers from the pkg_resources slowness bug?)

**Comment by jensens** [comment]
> (1) why is the version necessary at all,

I do not think it is needed, it more to support ancient ways of determining the version. The reason we have it in Plone is exact that: Keeping code backward compatible.

**Comment by jamadden** [comment]
> I believe that file does not get installed when you pip install zope.interface, as pip has some other, better way of supporting namespace packages.

It's setuptools that handles this. setuptools creates a '-nspkg.pth' file when it installs distributions that declare namespace packages, just like our `__init__.py` does. When pip or setuptools does the installation, that file winds up in `site-packages` (alongside a '.egg-link' file if it's an editable install, or the real package if not). There's [some magic in the auto-imported stdlib site.py](https://docs.python.org/3/library/site.html) that finds and *executes* all "*.pth" files in one of a few standard directories, including `site-packages`. (That file also winds up in built wheels, and is installed in the same way.)

When buildout does the installation, sometimes the -nspkg.pth winds up in the .egg directory, and sometimes it doesn't; I don't know what the difference is (possibly which version of buildout I used when the eggs got put in the cache). But it doesn't matter, I think, because `site.py` won't find and discover those; even though they're on `sys.path`, they aren't in one of the four magic directories.

This is what the distributed `zope.interface-4.6.0-py2.7-nspkg.pth` looks like, btw:
```python
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('zope',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('zope', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('zope', [os.path.dirname(p)])));m = m or sys.modules.setdefault('zope', types.ModuleType('zope'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
```
