### ISSUE TITLE
PyPy 3.7 alpha has unexpected attribute __orig_bases__

### ISSUE THREAD

**Issue by mattip** [zopefoundation/zope.interface#213]
I am not sure whether this is a PyPy bug or a problem with zope.interface. When I run with the [soon-to-be-released pypy for python3.7](https://buildbot.pypy.org/pypy/) (note the rc2 downloads) with zope, I get an error in [`__compute_attrs`](https://github.com/zopefoundation/zope.interface/blob/master/src/zope/interface/interface.py#L791) since it tries to update the built-in `__orig_bases__`. Adding that attribute just after `__qualname__` on line 812 makes the tests pass. Is this a problem with PyPy or should this be fixed in zope.interface? This error does not appear in PyPy 3.6.

**Comment by mattip** [comment]
The [commit that added it to PyPy](https://foss.heptapod.net/pypy/pypy/-/commit/1aaa3e43fa607c45e68a9a83092f42de7700e879) for python3.7 remarks "Implemented __mro_entries__ from PEP 560"

**Comment by jamadden** [comment]
The problem doesn't appear in CPython 3.7/3.8 either, so it's definitely a difference of behaviour.

 `__orig_bases__` isn't something defined or used by `zope.interface` as far as I recall.  I assume that's [PEP 560](https://www.python.org/dev/peps/pep-0560/)?

CPython definitely keeps that attribute writable. Lifting an example from the PEP:
```pycon
>>> class GenericAlias:
...     def __init__(self, origin, item):
...         self.origin = origin
...         self.item = item
...     def __mro_entries__(self, bases):
...         return (self.origin,)
...
>>> class NewList:
...     def __class_getitem__(cls, item):
...         return GenericAlias(cls, item)
...
>>> class Tokens(NewList[int]):
...     pass
...
>>> Tokens.__orig_bases__
(<__main__.GenericAlias object at 0x10b2a7370>,)
>>> Tokens.__orig_bases__ = 1 # And it's writable
>>>
```

For full compatibility it would be nice if that attribute was writable everywhere, including on PyPy. The PEP says other use is discouraged, it doesn't say prohibited :) 

That said, I don't see anything wrong with excluding it in `__compute_attrs`.

However, I'm curious: Since that attribute is involved with typing and generic class items, I'm wondering how it's even getting here. CPython doesn't add that attribute to arbitrary types. Is PyPy always setting it? Do you have a specific example that fails?

**Comment by mattip** [comment]
The problem is that attribute is a tuple, so it fails the `_update_value` function. Should we be wrapping it differently?

> Do you have a specific example that fails?

Here is the traceback
```
======================================================================
ERROR: zope.interface (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: zope.interface
Traceback (most recent call last):
  File "/home/matti/pypy_stuff/pypy/tmp37/pypy3.7-v7.3.2rc2-linux64/lib-python/3/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/home/matti/pypy_stuff/pypy/tmp37/pypy3.7-v7.3.2rc2-linux64/lib-python/3/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/matti/pypy_stuff/zope.interface/src/zope/interface/__init__.py", line 57, in <module>
    _wire()
  File "/home/matti/pypy_stuff/zope.interface/src/zope/interface/interface.py", line 1117, in _wire
    from zope.interface.interfaces import IElement
  File "/home/matti/pypy_stuff/zope.interface/src/zope/interface/interfaces.py", line 255, in <module>
    class IInterface(ISpecification, IElement):
  File "/home/matti/pypy_stuff/zope.interface/src/zope/interface/interface.py", line 787, in __init__
    self.__attrs = self.__compute_attrs(attrs)
  File "/home/matti/pypy_stuff/zope.interface/src/zope/interface/interface.py", line 807, in __compute_attrs
    for aname, aval in attrs.items()
  File "/home/matti/pypy_stuff/zope.interface/src/zope/interface/interface.py", line 816, in <dictcomp>
    and aval is not _decorator_non_return
  File "/home/matti/pypy_stuff/zope.interface/src/zope/interface/interface.py", line 802, in update_value
    raise InvalidInterface("Concrete attribute, " + aname)
zope.interface.exceptions.InvalidInterface: Concrete attribute, __orig_bases__

```

**Comment by jamadden** [comment]
The difference is that CPython doesn't create an `__orig_bases__` attribute in this case, but PyPy does. Since there are no `__mro_entries__()` methods in the hierarchy, I think I would agree with CPython that there shouldn't be an `__orig_bases__` set either. But the PEP leaves that a bit ambiguous. It'll be interesting to look more closely at the implementation logic.

"This case" is `IInterface`, where PyPy has `{...'__orig_bases__': (<InterfaceClass zope.interface.interfaces.ISpecification>, <InterfaceClass zope.interface.interfaces.IElement>)}`. It's interesting that none of the `IWhatever` classes declared earlier in `interfaces.py` wind up with `__orig_bases__`, only `IInterface`. That's the first object that has two bases (`class IInterface(ISpecification, IElement):`) instead of just one.

**Comment by jamadden** [comment]
I think I *might* see an error in PyPy. I could easily be wrong, my RPython is rusty at best.

```python
def _update_bases(space, w_bases):
    bases_w = space.listview(w_bases)
    new_bases_w = []
    changed = False
...	
    if not changed:
        return bases_w
    return new_bases_w
…
def build_class(…):
    orig_bases_w, kwds_w = __args__.unpack()
    w_orig_bases = space.newtuple(orig_bases_w)
    bases_w = _update_bases(space, w_orig_bases)	
...
    if bases_w is not orig_bases_w:
        space.setitem(w_namespace, space.newtext("__orig_bases__"), w_orig_bases)
```

`build_class` checks to see if `bases_w`, returned from `_updated_bases`, changed or not by comparing it by identity with the original value. But there's some casting with `newtuple` and `listview` going on that might make identity unreliable: the first thing `_update_bases` does is get a `listview`  and that's what it returns, even if there were no `__mro_entries__`? I could imagine that this is different for one-element tuples than for multi-element tuples...

**Comment by arigo** [comment]
Thanks for looking it up.  I could figure it out and fix it based on your hints.  The problem is that `space.fixedview()` returns usually the same list as the one originally given to `space.newtuple()`, unless it's a list of exactly two elements---we have an optimization for all tuples of length 2...

**Comment by jamadden** [comment]
I can confirm that adding `Interface` to the end of the affected `class` statements, thus making bases a 3-tuple, lets zope.interface be imported. The unit tests then all run.  Thanks!

PyPy issue: https://foss.heptapod.net/pypy/pypy/-/issues/3302#note_144340
commit: https://foss.heptapod.net/pypy/pypy/-/commit/331c3978ad27497652643dcb46f8d94ad4ab74b8
