### ISSUE TITLE
C implementation of `@implementer` leaks objects

### ISSUE THREAD

**Issue by richvdh** [zopefoundation/zope.interface#216]
It appears that the C implementation of `@implementer` has a reference leak. This leads to a gradual increase in GC time, in a long-running application.

The following test script:

```python
#!/usr/bin/env python

import gc
from zope.interface.declarations import implementer
from zope.interface.interface import Interface

for i in range(20000):
    @implementer(Interface)
    class TestClass:
        pass

    if i % 1000 == 0:
        gc.collect()
        n = len(gc.get_objects())
        print("After %i cycles: %i objects" % (i, n))
```

produces the following output:

```
After 0 cycles: 8199 objects
After 1000 cycles: 45199 objects
After 2000 cycles: 82199 objects
After 3000 cycles: 119199 objects
After 4000 cycles: 156199 objects
After 5000 cycles: 193199 objects
After 6000 cycles: 230199 objects
After 7000 cycles: 267199 objects
After 8000 cycles: 304199 objects
After 9000 cycles: 341199 objects
After 10000 cycles: 378199 objects
After 11000 cycles: 415199 objects
After 12000 cycles: 452199 objects
After 13000 cycles: 489199 objects
After 14000 cycles: 526199 objects
After 15000 cycles: 563199 objects
After 16000 cycles: 600199 objects
After 17000 cycles: 637199 objects
After 18000 cycles: 674199 objects
After 19000 cycles: 711199 objects
```

In other words, each invocation of `@implementer` leads to new objects which cannot be garbage-collected.

Disabling the C implementations (by moving aside the `_zope_interface_coptimizations.cpython-36m-x86_64-linux-gnu.so` file) resolves the problem, as does downgrading to zope.interface 4.7.2.

**Comment by richvdh** [comment]
`git bisect` suggests the problem was introduced in ddf670afb792b7f7849d6383f31cac3273811edf.

**Comment by jamadden** [comment]
Thanks for the report. I’ll look into it tomorrow unless someone sees the problem first.

**Comment by richvdh** [comment]
This patch seems to make the problem go away. I'm not really familiar enough with either zope.interfaces or the Python C API to say for certain if it is correct (or complete):

```
diff --git a/src/zope/interface/_zope_interface_coptimizations.c b/src/zope/interface/_zope_interface_coptimizations.c
index 346e7f2..0764bde 100644
--- a/src/zope/interface/_zope_interface_coptimizations.c
+++ b/src/zope/interface/_zope_interface_coptimizations.c
@@ -359,6 +359,7 @@ Spec_traverse(Spec* self, visitproc visit, void* arg)
 static int
 Spec_clear(Spec* self)
 {
+    Py_CLEAR(self->_bases);
     Py_CLEAR(self->_implied);
     Py_CLEAR(self->_dependents);
     Py_CLEAR(self->_v_attrs);
```

Suffice it to say that `SpecificationBase._bases` seems to confuse the garbage collector.

**Comment by jamadden** [comment]
Thanks, that does indeed look like the problem. `Spec->_bases` was added in https://github.com/zopefoundation/zope.interface/commit/ab0466e56c6328407c3839a3a392cb127dbdb282 (https://github.com/zopefoundation/zope.interface/pull/155/), but was [simply overlooked in both `Spec_traverse` *and* `Spec_clear`](https://github.com/zopefoundation/zope.interface/pull/155/files#diff-f68fd39e6cf94748a382d0d560feb115R271-R305).

@richvdh I'm curious. My group has been running applications with uptimes measured in weeks and hasn't noticed this issue; they heavily use zope.interface/zope.component/zope.site and Pyramid. Would you say your application is a typical user of zope.interface, or is it somewhat unusual in the amount of dynamic specifications it creates?

**Comment by jensens** [comment]
I have a Plone 5.2.2 site using the latest zope.interface, running with some unexpected memory behaviour, growing slowly over several days from initial 400-500MB to 3GB (my limit when it restarts the process). There are that many possible factors what's wrong, it is difficult to tell if this could be the reason. Also, I need to enhance my memory-leak debugging skills... 

But when fixed I can update the service immediately using a branch and report back (needs some days).

**Comment by richvdh** [comment]
@jamadden good stuff, seems like an easy fix.

Our application is based on top of [Twisted](https://twistedmatrix.com/trac/), which uses zope.interface internally. I couldn't really say exactly what it is doing that is causing the problem here; a couple of things came to mind:
 * It does create a new dynamic specification via `@provider` for every outgoing TCP connection (here: https://github.com/twisted/twisted/blob/twisted-20.3.0/src/twisted/internet/endpoints.py#L918). With that said, I couldn't actually reproduce this problem with `@provider`, for reasons I haven't really dug into.
 * It explicitly calls `directlyProvides` for each TLS connection. 

Again, I'm not sure if those are the actual problem here, because I struggled to reproduce the problem outside our application. But they do look like dynamic behaviour that Zope might not expect, but that all Twisted-based applications are likely to hit.

**Comment by richvdh** [comment]
@jensens An interesting artifact of our experince was that, because the retained objects were tiny (1- or 2-tuples), the increase in memory usage was barely perceptible. We (or rather, our users) noticed it via increased GC time *despite* a relatively flat memory consumption.

**Comment by d-maurer** [comment]
Jason Madden wrote at 2020-9-28 03:48 -0700:
> ...
>@richvdh I'm curious. My group has been running applications with uptimes measured in weeks and hasn't noticed this issue; they heavily use zope.interface/zope.component/zope.site and Pyramid. Would you say your application is a typical user of zope.interface, or is it somewhat unusual in the amount of dynamic specifications it creates?

`z3c.form` seems to allow for instance (rather than class/interface) specific
adaptation. I do not know how this is achieved (as adaptation
primarily is based on interface specifications). It might be that
interface specification are dynamically created from instances; in this
case, a high number of specifications would be possible.

**Comment by jamadden** [comment]
Thanks everyone, this all makes sense. Given a scenario like this:
```python
# Static interface definition, static class definition
class IFoo(Interface):
    pass
class Bar(object):
    pass

# Something done per-request/connection/etc
bar = Bar()
alsoProvides(bar, IFoo)
```

The `bar` object now has a `__provides__` attribute that is-a `SpecificationBase` (the problematic object). Such usage is not at all uncommon. 

The contents of the leaking `SpecificationBase.__bases__` will be `(IFoo, <implementedBy Bar>)` — two static objects. The only thing that was newly allocated is the tuple itself. So memory growth would be quite small (56 bytes on my system), while the total number of objects (tuples) grows per-request/whatever. 

It's possible our application is subject to this but we've tuned GC to run rarely, accepting the occasional large pause. So we may not have noticed a slow growth in something that was already large. It's also possible our monitoring or metrics alerting just weren't capturing this, I haven't double-checked [/cc @sajones @cutz].

I think #217 should be the fix. If reviewed and accepted I can immediately release the patched version to PyPI.

**Comment by jensens** [comment]
In Plone we use z3c.form and other mechanisms to dynamically assign (even per request) interfaces. Also our tuples might be heavier than usual. So, this could be the reason for my observed memory leaks. I started a Plone `buildout coredev` test-run with the fixes. If this goes green I would consider the patch at least w/o side effects. My next check will be using the branch in my live site with the memory leaking problems.

**Comment by d-maurer** [comment]
Jens W. Klein wrote at 2020-9-28 12:10 -0700:
>In Plone we use z3c.form and other mechanisms to dynamically assign (even per request) interfaces. Also our tuples might be heavier than usual. So, this could be the reason for my observed memory leaks. I started a Plone `buildout coredev` test-run with the fixes. If this goes green I would consider the patch at least w/o side effects. My next check will be using the branch in my live site with the memory leaking problems.

In addition, `alsoProvides` is applied to any request
(to support the "browserlayer" functionality).

**Comment by jensens** [comment]
> In addition, `alsoProvides` is applied to any request
> (to support the "browserlayer" functionality).

Indeed, and this together with lineage subsites (additional own browserlayers) and plone.subrequest (Mosaic). That is a lot `alsoProvides` per request.

**Comment by jamadden** [comment]
Indeed, each intermediate `alsoProvides()` *replaces* the `__provides__` attribute, it doesn't augment it. Thus each individual call to `alsoProvides` would leak a tuple. Likewise for `noLongerProvides` or anything else built on`directlyProvides`.

**Comment by jensens** [comment]
One test fails now. Python 3.7 only (3.6 and 3.8 tests are passing):
https://jenkins.plone.org/job/pull-request-6.0-3.7/36/testReport/junit/plone.dexterity.tests.test_fti/TestFTIEvents/test_dynamic_schema_refreshed_on_modify_schema_policy/
The actual problem is in https://github.com/plone/plone.supermodel/blob/master/plone/supermodel/utils.py#L338
I really have no idea why this fails in Py 3.7 only...

**Comment by jamadden** [comment]
I'm not sure what that report is telling us, the stack trace seems to have left out the actual error. But guessing from `<weakref at 0x7fa19db030b0; to 'InterfaceClass' at 0x7fa19e39a9e0 (IBlank)>`, something was relying on a weak ref still existing that no longer does. That makes a certain amount of sense as we are now clearing a reference to whatever was in `__bases__` (of previous specifications) where before they were allowed to leak. Is it a `KeyError`?

Note that *setting* `__bases__` did not change in this PR. All that changed was the behaviour when an object was deallocated. Setting `__bases__`, and managing the refcounts for that, is handled entirely by CPython (we expose the field of the struct as a `getset` member, and CPython essentially generates the `@property` code to handle all conversion and refcounting).

**Comment by jensens** [comment]
Either I'm not sure what it tells me. Maybe a wrong implementation on Plone side, mytbe test specific. This is the the pain code, where zope.interface is used in a very dynamic way. But strange, it only appears in Python 3.7?

**Comment by d-maurer** [comment]
Jens W. Klein wrote at 2020-9-30 01:30 -0700:
>Either I'm not sure what it tells me. Maybe a wrong implementation on Plone side, mytbe test specific. This is the the pain code, where zope.interface is used in a very dynamic way. But strange, it only appears in Python 3.7?

Maybe, the error is related to some kind of non-determinism
(e.g. a race condition). In this case, you may see
the error only occasionally - and the next test runs might show
3.7 successful and another Python version test may show a problem.

**Comment by jensens** [comment]
Update: 
- retry tests on Jenkins now: fails
- local testing, on Python 3.7.8 running plone.dexterity tests only: works

Jenkins uses 3.7.6, so I installed this version on my machine.

- local testing, on Python 3.7.8 running plone.dexterity tests only: works

Maybe the test are failing only in combination with other tests, as Jenkins on Python 3.7.6 does: 
- local testing all tests, on Python 3.7.8 with all tests: fails!
- local testing all tests, on Python 3.7.6 with all tests: fails!
- local testing all tests, on Python 3.7.8 with all tests: works!

So I have still no clue why, but it is a problem on Python 3.7 only running the tests in combination.

**Comment by richvdh** [comment]
Forgive my naivety, but this sounds like a problem specific to plone which is being uncovered by this fix in zope.interface. Shouldn't it be tracked in an issue on that repository?

**Comment by jensens** [comment]
@richvdh I dont think this is Plone specific. Before the fix all worked w/o any problems. Other projects can be affected as well.

**Comment by jensens** [comment]
Full traceback
```
Error in test test_dynamic_schema_refreshed_on_modify_schema_policy (plone.dexterity.tests.test_fti.TestFTIEvents)
Traceback (most recent call last):
  File "/srv/python3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/srv/python3.7/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/home/jenkins/.buildout/eggs/cp37m/plone.dexterity-2.9.8-py3.7.egg/plone/dexterity/tests/test_fti.py", line 750, in test_dynamic_schema_refreshed_on_modify_schema_policy
    DexterityFTIModificationDescription('schema_policy', '')
  File "/home/jenkins/.buildout/eggs/cp37m/plone.dexterity-2.9.8-py3.7.egg/plone/dexterity/fti.py", line 561, in ftiModified
    syncSchema(model.schema, schema, overwrite=True, sync_bases=sync_bases)
  File "/home/jenkins/.buildout/eggs/cp37m/plone.supermodel-1.6.2-py3.7.egg/plone/supermodel/utils.py", line 338, in syncSchema
    dest.__bases__ = tuple(bases)
  File "/home/jenkins/workspace/pull-request-6.0-3.7@2/src/zope.interface/src/zope/interface/interface.py", line 402, in __setBases
    b.unsubscribe(self)
  File "/home/jenkins/workspace/pull-request-6.0-3.7@2/src/zope.interface/src/zope/interface/interface.py", line 389, in unsubscribe
    n = self._dependents[dependent]
  File "/home/jenkins/shiningpanda/jobs/69a88cbb/virtualenvs/0dd3bfc1/lib/python3.7/weakref.py", line 396, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7fa19db030b0; to 'InterfaceClass' at 0x7fa19e39a9e0 (IBlank)>
```

`self._dependents` is a `WeakKeyDictionary`. It assumes on unsubscribe that the key exists.  For some reason its gone on Python 3.7.

**Comment by mgedmin** [comment]
Perhaps adding a `gc.collect()` in the right place would make the test fail more reliably (and perhaps also on other Python versions)?

**Comment by richvdh** [comment]
@jensens fair enough. that does look odd.

**Comment by jamadden** [comment]
What's really interesting is that it's *self* that seems to have been collected!

```python
    def unsubscribe(self, dependent):
        try:
            n = self._dependents[dependent] # Line 389
        except TypeError:
            raise KeyError(dependent)

    def __setBases(self, bases):
        # Remove ourselves as a dependent of our old bases
        for b in self.__bases__:
            b.unsubscribe(self) # Line 402

```

So `b.unsubscribe(self)` turns into `b._dependents[self]`, which raises a `KeyError`. 

Nominally, *self* could not have been collected while we're running methods of *self* and passing *self* as an argument...

**Comment by jamadden** [comment]
This is complicated by the fact that many functions in the `test_fti` module create an interface called `IBlank`.

Interfaces are hashed based on just their name and module. So every one of these local `IBlank` interfaces will hash the same way, and be treated the same for purposes of `_dependents`.

If one of these `IBlank` was involved in a cycle that delayed its collection (and removal from `_dependents`) then later when GC ran, an *active* `IBlank` could be removed from `_dependents`. When we attempt to change the bases and remove `IBlank`, because the dead `IBlank` has just been collected and removed from `_dependents`, we would get this `KeyError`. 

It's highly dependent on when GC runs, and assumes the existence of a cycle and that some base object persists between test functions so that GC can clear out the living entry. I'm working on a simple reproducer, but I suspect that the problem could be solved by either (a) adding `gc.collect()` to `tearDown()` or (b) using a different name for `IBlank` in some of these functions.

Why is this issue showing up only now? Before the PR, the contents of `__bases__` were not subject to garbage collection, so the leak would prevent their weak refs from being cleaned up.

**Comment by jamadden** [comment]
Ok, this demonstrates it pretty easily:

```python
import gc
from zope.interface import Interface

class IRoot(Interface):
    pass

class IBlank(Interface):
    pass

IBlank.__bases__ = (IRoot,)
# IRoot now has IBlank in its _dependents
other_ref = IBlank # Keep alive
class IBlank(Interface): # Replace the original IBlank; this will hash identically
    pass

# Register the new IBlank as a dependent of IRoot.
IBlank.__bases__ = (IRoot,)

# Really, there should be two
print(list(IRoot._dependents.keys())) # -> [IBlank]

# Delete the original IBlank, which should remove it
# from _dependents. It takes a gc.collect() to do this,
# so there's a cycle somewhere.
del other_ref
gc.collect()
print(list(IRoot._dependents.keys())) # -> []

IBlank.__bases__ = (IRoot,) # KeyError
```

```console
$ python foo.py
[<InterfaceClass __main__.IBlank>]
[]
Traceback (most recent call last):
  File "/tmp/foo.py", line 29, in <module>
    IBlank.__bases__ = (IRoot,)
  File "//src/zope/interface/interface.py", line 402, in __setBases
    b.unsubscribe(self)
  File "//src/zope/interface/interface.py", line 389, in unsubscribe
    n = self._dependents[dependent]
  File "//lib/python3.8/weakref.py", line 383, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x10ce7ed10; to 'InterfaceClass' at 0x10ce71dd0 (IBlank)>
```

**Comment by jensens** [comment]
Well, since we hit a very specific edge case, I can grep through our code and remove those occurrences. This is probably in tests only. I would prefer to have it it fixed, but at least it needs a line in the changelog and some lines in the documentation.

**Comment by jamadden** [comment]
I recall running into this exact problem before, with older versions of zope.interface, so it's not new; it just took a brief hiatus in zope.interface 5 because of this bug. (It was more frequent on PyPy because of its non-refcount GC. I seem to recall adding fixes for that to some public zopefoundation repositories before...) It's for that reason that I learned to be careful about using local interface classes and especially how they're named 😄

**Comment by jamadden** [comment]
Given that we can't change equality/sorting/hashing of these objects without major BWC and persistence problems, the only way to fix this with minimum compatibility issues that I've been able to think of is to make `_dependents` identity based, e.g., `WeakValueDictionary` of `self._dependents[id(dependent)] = dependent`.

That has its own BWC concerns though. All of `subscribe()`, `unsubscribe()` and `dependents` are public methods or attributes. They're not documented as part of the interface, nor do they have docstrings, but given how handy they are, I'm sure they must be used outside this project, so changing the semantics of `subscribe/unsubscribe` away from hashed based could break…something…through the inverse of what's going on here. More likely, changing `dependents` from `{dependent: number of times subscribed}` to `{id: dependent}` would break the way anything finds actual dependent objects. We could use a `@property` to provide the old interface, but it would be disconnected from the backing data store, so direct changes to it wouldn't be reflected in the actual subscribers.

(I don't fully understand why `dependents` tracks the number of times something has subscribed. It must be intended to support nested calls, or subscribing the same object from multiple places. But it's not clear to me why that would actually happen. That complicates using a `WeakValueDictionary`, and we'd probably have to get into a custom datastructure to make it work.)

**Comment by jensens** [comment]
I renamed the interfaces to have unique names in https://github.com/plone/plone.dexterity/pull/135 and tests are passing.

**Comment by jamadden** [comment]
5.1.1 is on PyPI (it may be awhile before binary wheels get built as Travis is busy.)

**Comment by cutz** [comment]
> It's possible our application is subject to this but we've tuned GC to run rarely, accepting the occasional large pause. So we may not have noticed a slow growth in something that was already large. It's also possible our monitoring or metrics alerting just weren't capturing this, I haven't double-checked [/cc @sajones @cutz].

@jamadden  @sajones I'm late to the party, but I wanted to shed some light on why we may not have noticed this. Our application has had large organic usage growth this year and when we couple that with the large zodb caches we run, we've been attributing any memory growth towards caches filling up. Combine that with what is likely slower growth in our, relatively speaking, large memory footprint application and I think it just went unnoticed. That said, we had been starting to key in on some hot processes that were showing growth which didn't make sense to attribute to ZODB caches given our database sizes.  We just hadn't tracked down any details yet.

Looking forward to seeing what sort of impact this has. Thanks All.

**Comment by d-maurer** [comment]
Jason Madden wrote at 2020-9-30 04:13 -0700:
>This is complicated by the fact that many functions in the `test_fti` module create an interface called `IBlank`.
>
>Interfaces are hashed based on just their name and module. So every one of these local `IBlank` interfaces will hash the same way, and be treated the same for purposes of `_dependents`.
>
>If one of these `IBlank` was involved in a cycle that delayed its collection (and removal from `_dependents`) then later when GC ran, an *active* `IBlank` could be removed from `_dependents`. When we attempt to change the bases and remove `IBlank`, because the dead `IBlank` has just been collected and removed from `_dependents`, we would get this `KeyError`.

Does this not sound like a conceptual bug in the treatment
of `_dependents`?. An application can name its interfaces at it likes
and this should not lead to `KeyError`s.

**Comment by jamadden** [comment]
Sort of? But `zope.interface` is hardly unique in this. Using weakrefs with objects that define non-identity hash functions can easily lead to this problem in many places in an application. Here's an example from the standard library:

```pycon
>>> from uuid import UUID
>>> from weakref import WeakKeyDictionary
>>> UUID('{12345678-1234-5678-1234-567812345678}')
UUID('12345678-1234-5678-1234-567812345678')
>>> uuid1 = UUID('{12345678-1234-5678-1234-567812345678}')
>>> uuid2 = UUID('{12345678-1234-5678-1234-567812345678}')
>>> uuid1 == uuid2
True
>>> hash(uuid1) == hash(uuid2)
True
>>> d = WeakKeyDictionary()
>>> d[uuid1] = 42
>>> d[uuid2]
42
>>> del uuid1
>>> d[uuid2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//python3.8/weakref.py", line 383, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x10ecca470; to 'UUID' at 0x10ec6f0f0>
```

I outlined some possible solutions and their drawbacks above. As rarely as this is actually a problem, I'm not sure it's worth the costs though.

It's worth noting that more than just hashing depends on interface names. Pickling is done by name too. No matter where in a module, or how many times, you define `IFoo`, when you pickle and unpickle it, you're going to get the module global named `IFoo`:

```pycon
>>> import pickle
>>> from zope.interface import Interface
>>> class IFoo(Interface):
...     pass
...
>>> s = pickle.dumps(IFoo)
>>> IFoo = 42
>>> pickle.loads(s)
42
```

**Comment by d-maurer** [comment]
Jason Madden wrote at 2020-9-30 10:44 -0700:
>Sort of? But `zope.interface` is hardly unique in this. Using weakrefs with objects that define non-identity hash functions can easily lead to this problem in many places in an application. Here's an example from the standard library:
>
>```pycon
>>>> from uuid import UUID
>>>> from weakref import WeakKeyDictionary
>>>> UUID('{12345678-1234-5678-1234-567812345678}')
>UUID('12345678-1234-5678-1234-567812345678')
>>>> uuid1 = UUID('{12345678-1234-5678-1234-567812345678}')
>>>> uuid2 = UUID('{12345678-1234-5678-1234-567812345678}')
>>>> uuid1 == uuid2
>True
>>>> hash(uuid1) == hash(uuid2)
>True
>>>> d = WeakKeyDictionary()
>>>> d[uuid1] = 42
>>>> d[uuid2]
>42
>>>> del uuid1
>>>> d[uuid2]
>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "//python3.8/weakref.py", line 383, in __getitem__
>    return self.data[ref(key)]
>KeyError: <weakref at 0x10ecca470; to 'UUID' at 0x10ec6f0f0>

>```

This is a different case. Here, we have `uuid1 == uuid2`
and therefore, after we deleted "uuid1" (and thereby removed it
implicitly from `d`) we expect a `KeyError` on `d[uuid2]`.

But, two definitions if an interface named *I*, should not be equal
-- strangely enough they are, however. For me, this looks like a bug:
```
>>> from zope.interface import Interface
>>> class I(Interface):
...   def f(): pass
...
>>> I1 = I
>>> class I(Interface):
...   def g(): pass
...
>>> I2 = I
>>> I1 == I2
True
>>> list(I1)
['f']
>>> list(I2)
['g']
```

Thus, we have two interfaces defining different methods
and nevertheless, they are considered equal.

**Comment by jamadden** [comment]
That's correct and expected. Only `__name__` and `__module__` are considered in comparisons.

One reason for interfaces to be comparable is so that they can be used as BTree keys — identity comparisons don't work in that case — in fact, they must be totally orderable, independent of process or current definition (because definitions change; methods and attributes are added or removed, but the comparison must remain valid).

**Comment by d-maurer** [comment]
Jason Madden wrote at 2020-9-30 12:01 -0700:
>That's correct and expected. Only `__name__` and `__module__` are considered in comparisons.

That is a very strange notion of "equality":
How could interfaces be considered equal which define completely
different sets of methods?

It should (at least) be documented with big warning signs as it makes
dynamic interface definitions highly unreliable.
The test failure discussed in the thread is one instance of this
unreliability.

As I wrote earlier, `z3c.form` provides some mechanism to register
adapters based on individual instances (rather than classes and interfaces).
I suspect dynamic interface definitions to be involved in this functionality
and with the above equality this might lead to big surprises.

**Comment by jamadden** [comment]
I think a big part of the reasoning goes to persistence. The only sane way to pickle an interface is as a global object — just like that's the only sane way to pickle a class. That's the only way that an instance of a class that `@implementer(ISomething)` and some other arbitrary instance that `alsoProvides(instance, ISomething)` can mean the same thing when unpickled. Once you understand that, then it's only logical that the name and module are the things considered in comparisons. After all, that's all that actually matters to persistence.

This comparison behaviour has been the same all the way back to at least [3.4.0](https://github.com/zopefoundation/zope.interface/blob/3.4.0/src/zope/interface/interface.py#L645). 

That early version didn't correctly define `__eq__` and `__hash__`, so it was inconsistent. Interfaces weren't totally ordered, and could compare differently depending on which operators you used (or worse, which internal operators a data structure used). It wasn't long before someone realised this, and 10 years ago [the present definition of equality was added](https://github.com/zopefoundation/zope.interface/commit/c7a10ce52ad99fb6528416678fc057e5338d3e2b).

Because this has been the behaviour for more than ten years, I suspect that this is all handled correctly by packages doing dynamic interfaces (IIRC, the "menu" support works be creating dynamic interfaces and making them global objects so they can be unpickled; it understands that names matter). It's only rare corner cases like the one in plone.dexterity — which only showed up because of a quirk of the garbage collector on a particular machine — where it becomes a problem.

**Comment by d-maurer** [comment]
Jason Madden wrote at 2020-9-30 21:23 +0000:
>I think a big part of the reasoning goes to persistence....

Conceptionally, it is wrong to consider two interfaces equal
if they define different sets of methods -- such interfaces
are obviously not equal (in the sense that they can be used
interchangeably).

Apparently, a specific requirement (maintaining interfaces in
a persistent `BTree`) has caused the adoption of such a strange
equality definition. This might be acceptable provided it is
well documented. Up to now, I have not yet consiously seen this
documentation.

**Comment by jamadden** [comment]
I believe that the correct perspective is that conceptually, an interface is a global object. By definition, there is only one global object at a time that can be referred to by `__module__.__name__`. Methods are irrelevant because *there is only one definition*. They may change from one invocation of the program to the next, but again, that doesn't matter. The stable identifier is the global identifier. 

Trying to define two global objects with the same module and name and use them at the same time as if they were distinct is conceptually quite wrong in this framework. Just as you can't define two `class A` objects and fully expect for them to work correctly at the same time (e.g., the two-argument `super(A, self)` is going to be broken; un/pickling will produce the most recently defined, not both).

At any rate, I feel like I've veered very far off what this issue was about and so I should stop annoying those getting notifications for this issue with unrelated chatter.

**Comment by d-maurer** [comment]
Jason Madden wrote at 2020-9-30 15:36 -0700:
>I believe that the correct perspective is that conceptually, an interface is a global object.

Really? Are you really using interfaces based on their property to
be "global object"s? I do not: I use them based on
what methods (with what signatures)
and attributes they define. For me, the "global object" property is at most
secondary.

> ...
>At any rate, I feel like I've veered very far off what this issue was about and so I should stop annoying those getting notifications for this issue with unrelated chatter.

I will check whether the documentation clearly states
that the interface semantics is primarily based on being a
"global object" (with the ramification for `equality`)
and if not file a new issue.
