### ISSUE TITLE
Wheels for MACOS Not working

### ISSUE THREAD

**Issue by genisysram** [zopefoundation/zope.interface#223]
### What I did:
The wheels for Macos for all the python versions were not working.
https://travis-ci.com/github/genisysram/zope.interface/builds/217067754
Please find the url where all the versions  were failing.

**Comment by icemac** [comment]
What does ”were not working" mean?
What did you do and what was the error message (complete traceback)?

**Comment by jamadden** [comment]
Examining the supplied Travis CI link, I see two problems, both of which appear completely unrelated to `zope.interface`:

- Running a script using f-strings on Python 2.7 and 3.5 fails since they don't support that syntax.
- The other versions of Python attempt to submit data to coveralls.io and that fails with a server-side rejection of an invalid request: `requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs`

**Comment by icemac** [comment]
Okay, I am going to close this issue then. Thank you @jamadden for examining it.

Feel free to reopen if there are still questions open. (I know we have to migrate this project to GHA, too, but it is a bit more complicated than the pure Python ones.)

**Comment by jamadden** [comment]
> I know we have to migrate this project to GHA, too, but it is a bit more complicated than the pure Python ones.

[zodb/perfmetrics](https://github.com/zodb/perfmetrics/blob/master/.github/workflows/tests.yml) is the latest project that builds native wheels on macos and manylinux that I've moved to GHA. I would do something like that here, but I know we're all-in on reusing tox and just flake8 so it can't be used as-is.

**Comment by icemac** [comment]
@jamadden Thank you for the hint, I noted it down at https://github.com/zopefoundation/meta/issues/63 for later use.
