### ISSUE TITLE
WARNING: Definition list ends without a blank line; unexpected unindent.

### ISSUE THREAD

**Issue by mtelka** [zopefoundation/zope.interface#278]
## BUG/PROBLEM REPORT

While running tests I noticed the following warning:
```
docstring of zope.interface.common.numbers.IReal.__trunc__:8: WARNING: Definition list ends without a blank line; unexpected unindent.
```
The same warning also appeared in #211.

### What I did:

Run tests for `zope.interface`

### What I expect to happen:

No warninigs displayed

### What actually happened:

```
docstring of zope.interface.common.numbers.IReal.__trunc__:8: WARNING: Definition list ends without a blank line; unexpected unindent.
```

### What version of Python and Zope/Addons I am using:

OpenIndiana Hipster
Python 3.9.16
zope.interface 6.1

**Comment by d-maurer** [comment]
Marcel Telka wrote at 2023-10-6 04:15 -0700:
> ...
>While running tests I noticed the following warning:
>docstring of zope.interface.common.numbers.IReal.__trunc__:8: WARNING: Definition list ends without a blank line; unexpected unindent.

Even though this warning references `zope.interface.common.numbers.IReal`,
the problem (almost surely) is in Python's `numbers.Real.__trunc__`.

If you check `zope.interface.common.numbers.IReal`, you will
find that it does not have a `__trunc__` definition.
Almost surely, the problem will go away, if you add a blank line
in Python's `numbers.Real.__trunc__` docstring before the
`i.e. "truncate towards 0".

Once you have verified that the problem comes from Python,
you can file a corresponding Python issue.

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
