### ISSUE TITLE
Optimized version of InterfaceBase doesn't use interface's __adapt__

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#3]
In https://bugs.launchpad.net/zope.interface/+bug/98488, Ben Artin reported:

> According to zope.interface documentation, the `__call__` of an interface should use `__adapt__` in the interface to attempt to adapt the object. This is not so with the optimized C version of `InterfaceBase`:

```
from zope.interface import Interface
class Test(Interface):
    pass
def adapt(*args, **kwargs):
    return 17
from new import instancemethod
Test.__adapt__ = instancemethod(adapt, Test)
print Test.__adapt__(1) # prints 17
Test(1) # Generates an exception
```

> This is not how `InterfaceBasePy.__call__` behaves -- it uses `interface.__adapt__`, which can be customized for each interface. This discrepancy between `InterfaceBasePy` and the C-optimized `InterfaceBase` should be eliminated; I believe that the behavior of `InterfaceBase` should change to match that of `InterfaceBasePy`.

@ctheune followed up:

> `__adapt__` is not documented in IInterface. However, the tests say that we do this and respect PEP 246 behaviour.

**Comment by jamadden** [comment]
This still appears to be the case and does still appear to be a discrepancy.

The discrepancy can be fixed either by changing InterfaceBasePy to use `adapter = InterfaceBasePy.__adapt__(self, obj)` instead of `self.__adapt__(obj)` or changing the C code to call the method instead of directly calling the `__adapt__` C function. The later is the more flexible change, the former is the de-facto status quo.

Thoughts?

**Comment by jamadden** [comment]
Good news/bad news.

The bad news: making the C extension call `self.__adapt__` slows calling interfaces down by 20% or so, compared to current master (there is a5-7% variance in the test times, so anything under 7% I considered insignificant):

| Benchmark                                                   | bench_master38 | bench_issue200               | bench_issue3                 |
|-------------------------------------------------------------|----------------|------------------------------|------------------------------|
| call interface (provides; deep)                             | 369 ns         | not significant              | 454 ns: 1.23x slower (+23%)  |
| call interface (provides; wide)                             | 373 ns         | not significant              | 457 ns: 1.22x slower (+22%)  |
| call interface (no alternate, no conform, not provided)     | 671 ns         | not significant              | 760 ns: 1.13x slower (+13%)  |
| call interface (alternate, no conform, not provided)        | 395 ns         | not significant              | 494 ns: 1.25x slower (+25%)  |
| call interface (alternate, invalid conform, not provided)   | 348 ns         | not significant              | 424 ns: 1.22x slower (+22%)  |
| query adapter (no registrations)                            | 3.23 ms        | not significant              | 3.68 ms: 1.14x slower (+14%) |
| query adapter (all trivial registrations)                   | 3.93 ms        | 4.40 ms: 1.12x slower (+12%) | 4.48 ms: 1.14x slower (+14%) |
| query adapter (all trivial registrations, wide inheritance) | 43.3 us        | not significant              | 49.0 us: 1.13x slower (+13%) |
| query adapter (all trivial registrations, deep inheritance) | 43.2 us        | 46.9 us: 1.09x slower (+9%)  | 49.1 us: 1.14x slower (+14%) |


The good news, though, is that it's still substantially faster than 4.7.2 was:

| Benchmark                                                   | bench_472 | bench_issue3                  | bench_master38                |
|-------------------------------------------------------------|-----------|-------------------------------|-------------------------------|
| call interface (provides; deep)                             | 653 ns    | 454 ns: 1.44x faster (-30%)   | 369 ns: 1.77x faster (-43%)   |
| call interface (provides; wide)                             | 647 ns    | 457 ns: 1.42x faster (-29%)   | 373 ns: 1.73x faster (-42%)   |
| call interface (no alternate, no conform, not provided)     | 953 ns    | 760 ns: 1.25x faster (-20%)   | 671 ns: 1.42x faster (-30%)   |
| call interface (alternate, no conform, not provided)        | 694 ns    | 494 ns: 1.41x faster (-29%)   | 395 ns: 1.76x faster (-43%)   |
| call interface (alternate, invalid conform, not provided)   | 654 ns    | 424 ns: 1.54x faster (-35%)   | 348 ns: 1.88x faster (-47%)   |
| read providedBy                                             | 62.9 ns   | 70.3 ns: 1.12x slower (+12%)  | not significant               |
| query adapter (no registrations)                            | 8.25 ms   | 3.68 ms: 2.24x faster (-55%)  | 3.23 ms: 2.55x faster (-61%)  |
| query adapter (all trivial registrations)                   | 9.33 ms   | 4.48 ms: 2.08x faster (-52%)  | 3.93 ms: 2.37x faster (-58%)  |
| query adapter (all trivial registrations, wide inheritance) | 99.1 us   | 49.0 us: 2.02x faster (-51%)  | 43.3 us: 2.29x faster (-56%)  |
| query adapter (all trivial registrations, deep inheritance) | 99.6 us   | 49.1 us: 2.03x faster (-51%)  | 43.2 us: 2.30x faster (-57%)  |
| sort interfaces                                             | 290 us    | 34.6 us: 8.40x faster (-88%)  | 32.3 us: 8.99x faster (-89%)  |
| sort mixed                                                  | 694 us    | 370 us: 1.88x faster (-47%)   | 361 us: 1.93x faster (-48%)   |
| contains (empty dict)                                       | 305 ns    | 62.4 ns: 4.88x faster (-80%)  | 60.0 ns: 5.08x faster (-80%)  |
| contains (populated dict: interfaces)                       | 320 ns    | 61.5 ns: 5.20x faster (-81%)  | 61.3 ns: 5.22x faster (-81%)  |
| contains (populated list: interfaces)                       | 51.1 us   | 3.55 us: 14.40x faster (-93%) | 3.43 us: 14.90x faster (-93%) |
| contains (populated dict: implementedBy)                    | 311 ns    | 62.3 ns: 4.99x faster (-80%)  | 59.5 ns: 5.22x faster (-81%)  |
| contains (populated list: implementedBy)                    | 51.9 us   | 28.0 us: 1.86x faster (-46%)  | 27.1 us: 1.92x faster (-48%)  |

Plus, it's a very simple change:
```patch
----------------------------------------------------------------
modified: src/zope/interface/_zope_interface_coptimizations.c
----------------------------------------------------------------
@@ -49,6 +49,7 @@ static PyObject *str_registry, *strro, *str_generation, *strchanged;
 static PyObject *str__self__;
 static PyObject *str__module__;
 static PyObject *str__name__;
+static PyObject *str__adapt__;

 static PyTypeObject *Implements;

@@ -835,7 +836,7 @@ ib_call(PyObject *self, PyObject *args, PyObject *kwargs)
       Py_DECREF(conform);
   }

-  adapter = __adapt__(self, obj); // XXX: should be self.__adapt__.
+  adapter = PyObject_CallMethodObjArgs(self, str__adapt__, obj, NULL);
   if (adapter == NULL || adapter != Py_None)
   {
       return adapter;
@@ -2023,6 +2024,7 @@ init(void)
   DEFINE_STRING(__self__);
   DEFINE_STRING(__name__);
   DEFINE_STRING(__module__);
+  DEFINE_STRING(__adapt__);
 #undef DEFINE_STRING
   adapter_hooks = PyList_New(0);
   if (adapter_hooks == NULL)
```
Since it's a simple change and the performance doesn't regress much, I would be in favor of letting interface subclasses define `__adapt__`. 

Except.

The fly in the ointment is that the natural way of defining `__adapt__`, in the class body, doesn't work. That becomes a Method definition. One must write it separately and then assign it, as in the example (`Test.__adapt__ = adapt` is sufficient if you don't need `self`). That's hardly ideal, but I don't think we can start taking `__adapt__` in the body to be an instance method without backwards compatibility issues. What if we used a new decorator to allow any interface definition to override any `Interface` methods?
```python
class IFoo(Interface):
    @override 
    def __adapt__(self, obj):
        …
    def __adapt__():
        "This actually becomes a Method of the interface."
```

I don't know if `super()` or `super(IFoo, self)` would work in those definitions automatically. That also wouldn't work for `__call__` automatically; I can imagine ways to make it do so, but I'd prefer to kick that can down the road.

**Comment by jamadden** [comment]
I've been giving this a bit more thought. I think it should be possible to leverage the class hierarchy and possibly our new metaclass and/or a `__new__` method to reduce the cost back to near-0 for classes that don't override `__adapt__`. (This would require that `__adapt__` be defined in the type, statically. Since it's not possible to define `__adapt__` at all right now, that shouldn't be an issue.) That's a little bit more work than the patch above, but not too much.

As for defining the implementation of `__adapt__`, while it would be possible to eliminate the decorator through inspecting the signature (does it have two arguments, the first of which is `self`?) "explicit is better than implicit." Also, the implicit version doesn't let us have both an implementation and a Method (unless we could do something with the new-ish Python 3 metaclass methods that let you define how the namespace is handled so we could keep multiple definitions. Which we can't, not yet.)
