### ISSUE TITLE
zope.interface 4.3.0 broke zodbbrowser

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.interface#55]
zope.interface 4.3.0 broke zodbbrowser.

Last successful build (zope.interface 4.2.0):
- https://jenkins.gedmin.as/job/zodbbrowser/658/console

First failing build (zope.interface 4.3.0 is the only version that changed):
- https://jenkins.gedmin.as/job/zodbbrowser/659/console

This is not related to #43 -- the build is still broken with zope.interface 4.3.1:
- https://jenkins.gedmin.as/job/zodbbrowser/660/console

Steps to reproduce
```
git clone https://github.com/mgedmin/zodbbrowser
cd zodbbrowser
make
bin/zodbbrowser --rw empty.fs
# now open http://localhost:8070/
```

Expected behavior:
![ekrano nuotrauka is 2016-09-02 10-02-53](https://cloud.githubusercontent.com/assets/159967/18195510/889923d6-70f4-11e6-921b-1e76fba2ed15.png)

Actual behavior:
![ekrano nuotrauka is 2016-09-02 10-04-13](https://cloud.githubusercontent.com/assets/159967/18195523/a2994fa4-70f4-11e6-8642-7b10d3d4ce69.png)

**Comment by mgedmin** [comment]
I've narrowed this down to the following statement in zope.container.traversal.ContainerTraverser.browserDefault:
```python
        view_name = getSiteManager(None).adapters.lookup(
            map(providedBy, (self.context, request)), IDefaultViewName)
```

`self.context` is a zope.site.folder.Folder object.  `request` is a zope.publisher.browser.BrowserRequest instance.

zope.interface 4.2.0 returns `u'zodbbrowser'`.  zope.interface 4.3.x returns `u'index.html'`.

My [site definition](https://github.com/mgedmin/zodbbrowser/blob/ac5a00dce22ac1021a27a48bc9d2586408a32002/src/zodbbrowser/standalone.py#L56-L59) explicitly asks for
```xml
          <browser:defaultView
              for="persistent.Persistent"
              name="zodbbrowser"
              xmlns:browser="http://namespaces.zope.org/browser" />
```

**Comment by jamadden** [comment]
So `browser:defaultView` winds up calling [registerAdapter](https://github.com/zopefoundation/zope.publisher/blob/master/src/zope/publisher/zcml.py#L105).

In this case that translates to

```python
registerAdapter('zodbbrowser', (persistent.Persistent, IBrowserRequest), IDefaultViewName, '', info)
``` 

(For reference, the signature of registerAdapter is 
```python
def registerAdapter(self, factory, required=None, provided=None,
                            name=u'', info=u'', event=True):
```
It's weird to be passing a string as the `factory`, but whatever...
).

I don't see [any relevant changes](https://github.com/zopefoundation/zope.interface/compare/4.2.0...4.3.1#diff-e92fa4ba4488a300b04dd1a578a2c7beL182) to `Components.registerAdapter`. The only thing that changed in it was the removal of the `_u` special function in favor of unicode literals. Likewise, that was [the only change](https://github.com/zopefoundation/zope.interface/compare/4.2.0...4.3.1#diff-c86eba753d2b1383fec5b59cce99a75fL21) to `adapters.py` as well (and the C interface optimizations haven't been touched in 5 years.)

The objects returned by `implementedBy` are now sortable, but I don't see where that enters in (and they retain their old equality and hashing semantics anyway).

**Comment by jamadden** [comment]
If I manually set this up, I get back the expected `zodbbrowser` string:
```python
>>> import persistent
>>> from zope import interface
>>> from zope.publisher.interfaces import IDefaultViewName
>>> from zope.publisher.interfaces.browser import IBrowserRequest
>>> from zope.publisher.interfaces.browser import IDefaultSkin
>>> from zope.component import getSiteManager
>>> gsm = getSiteManager()
>>> gsm.registerAdapter('zodbbrowser', (persistent.Persistent, IBrowserRequest), IDefaultViewName, '')
>>> @interface.implementer(IBrowserRequest)
...: class MockRequest(object):
...:     pass
...:
>>> context = persistent.Persistent()
>>> gsm.adapters.lookup( map(interface.providedBy, (context, MockRequest())), IDefaultViewName)
'zodbbrowser'
```

This is using 4.3.1:
```
$ pip show zope.interface
---
Metadata-Version: 2.0
Name: zope.interface
Version: 4.3.1
...
```

**Comment by jamadden** [comment]
> (and they retain their old equality and hashing semantics anyway).

Which...seems to somehow be the source of the problem?

```python
class Implements(Declaration):

    def __eq__(self, other):
        return self is other
```

The `__eq__` method was added for 4.3.0. Prior to 4.3.0, there was no `__eq__` implemented by `Implements` or its super classes. I sure *thought* that the default equality test was identity based, but I obviously must have missed something. Commenting out the `__eq__` implementation fixes zodbbrowser.

If I print some debuging info, I can see the failing test equality test being done by the `lookup` method: `('Comparing', <implementedBy persistent.Persistent>, 'is', <implementedBy persistent.Persistent>, False)`

So that's weird, I'm not quite sure how the equality worked before. I'm also not quite sure how we ended up having multiple `<implementedBy>` for the same class, those are supposed to be aggressively cached.

**Comment by jamadden** [comment]
Ah, it turns out that one of the objects is a zope.security Proxy. It does provide an implementation of `__eq__` which compares the underlying object. So if `Implements` doesn't provide `__eq__`, then `self == other` would get reversed by the interpreter to  `other == self` which would then invoke the Proxy method, unwrap the object and ultimately wind up comparing via identity.

So I *think* we can fix this by simply not providing an implementation of `__eq__` and `__ne__` in `Implements`. That's just weird though, since there are implementations of `__lt__`, `__le__`, etc.

**Comment by jamadden** [comment]
#56 should fix it. There are tests and doc comments about this now. I went with simply eliding the `__eq__` and `__ne__` methods as that seemed cleanest and least error prone.

**Comment by mgedmin** [comment]
OMG.

Thank you for digging into this!
