### ISSUE TITLE
zope.interface 4.3.3 causes warning in valgrind

### ISSUE THREAD

**Issue by gmnash** [zopefoundation/zope.interface#69]
The following occurs when running valgrind on a python script that loads zope.interface 4.3.3 but not zope.interface 4.3.2.

==13973== Warning: DWARF2 reader: Badly formed extended line op encountered

Tested on valgrind 3.10.1 and 3.12.  zope.interface 4.3.3 causes valgrind 3.10.1 to log the warning then crash, but valgrind 3.12 logs it as a warning and continues execution.

zope.interface installed via continuum public defaults conda repository.  Running xubuntu 14.04 with conda 4.2.13 and python 2.7.11.

**Comment by jamadden** [comment]
There was [only one (minor)](https://github.com/zopefoundation/zope.interface/compare/4.3.2...4.3.3#diff-f68fd39e6cf94748a382d0d560feb115) change to the C files for zope.interface between those versions, defining a constant. And that only applies to Python 3.

Since DWARF is a debugging data format, this suggests to me a build/compiler issue. Can you reproduce this if you install zope.interface from PyPI?

**Comment by gmnash** [comment]
Cannot reproduce when removing conda package of zope.interface 4.3.3 and then installing zope.interface 4.3.3 via pip.  Feel free to close, and I will try and find the person that builds the conda package.  Thanks for the quick response.
