### ISSUE TITLE
Base class with interface interrupts adapter registered for a class

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#8]
In https://bugs.launchpad.net/zope.interface/+bug/226112, @ctheune reports:

> See the attached patch for a failing test case.
> 
> (Patch applicable against zope.interface trunk)
> 
> We're not sure whether this is right or wrong but we feel the intended behaviour is what our test expects.

The patch adding a testcase: https://bugs.launchpad.net/zope.interface/+bug/226112/+attachment/290210/+files/weird-bug.patch

**Comment by jamadden** [comment]
In case it goes away, below is the proposed scenario. I confirm that it still happens as described in master as of this writing.

> We start with an empty registry:
```pycon
>>> registry = AdapterRegistry()
```
> We create an interface that we want to adapt to later:
```pycon
>>> class IDefaultViewName(zope.interface.Interface):
...     pass
```
> And a base class:
```pycon
>>> class Context(object):
...     pass
```
> We register two adapters. A general one and one for the Context class:
```pycon
>>> registry.register([None], IDefaultViewName, '', 'index.html')
>>> registry.register([zope.interface.implementedBy(Context)], IDefaultViewName, '', 'index')
```
> We create two model classes which subclass from our base class. The first is a simple subclass:
```pycon
>>> class RDBModel(Context):
...     pass
```
> The other subclasses Context and a class which declares another interface:
```pycon
>>> class IOther(zope.interface.Interface):
...     pass
>>> class OtherBase(object):
...     zope.interface.implements(IOther)
>>> class Model(OtherBase, Context):
...     pass
```
> Our RDBModel gets the specific adapter:
```pycon
>>> model = RDBModel()
>>> registry.lookup((zope.interface.providedBy(model),), IDefaultViewName, '')
'index'
```
> And our Model should too:

[But does not. This was originally written to be a failing doctest, so it showed `'index'`, but what you really get right now is what's below: `'index.html'`]

```pycon
>>> model = Model()
>>> registry.lookup((zope.interface.providedBy(model),), IDefaultViewName, '')
'index.html'
```

So the key points are:

1. `RDBModel` implements only `IOther`:
```pycon
>>>  list(zope.interface.providedBy(model).flattened())
[<InterfaceClass __main__.IOther>, 
 <InterfaceClass zope.interface.Interface>]
```

2. `RDBModel` *subclasses* `Context`
```pycon
>>> RDBModel.mro()
[__main__.RDBModel, __main__.Context, object]
```

3. `Context` implements nothing
```pycon
>>> list(zope.interface.providedBy(Context()).flattened())
[<InterfaceClass zope.interface.Interface>]
```

4. There is an adapter registered for `Context` and one registered for anything.
5. `RDBModel` gets the adapter registered for anything, not the one registered for `Context`
6. Yet, if we only extend `Context` and do not implement anything else, we get the adapter registered for `Context`.
```pycon
>>> class ExtendsContextOnly(Context):
...:     pass
>>> model = ExtendsContextOnly()
>>> registry.lookup((zope.interface.providedBy(model),), IDefaultViewName, '')
'index'
```


In general, interface declarations on subclasses trump those of parent classes. That's correct, otherwise the interface hierarchy would strictly mirror the class hierarchy, rendering it substantially less useful.

The trouble seems to arise when interfaces (and adapters on them) are mixed with classes (and adapters on them). I think it's a fairly common practice to register an adapter for a specific class as a sort of last word, "really use this", `!important` (in CSS terms) override. And that works fine, right up until you subclass that class and implement a new interface. Then the results might be unexpected.

The issue can be seen in the `__sro__` of the `providedBy()` for `Model`:
```pycon
>>> zope.interface.providedBy(Model()).__sro__
(<implementedBy __main__.Model>,
 <implementedBy __main__.OtherBase>,
 <InterfaceClass __main__.IOther>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __main__.Context>,
 <implementedBy __builtin__.object>)
```

In this case, the bases for `<implementedBy __main__.Model>` are `(<implementedBy __main__.OtherBase>, <implementedBy __main__.Context>)` and the bases for `<implementedBy __main__.OtherBase>` are `(<InterfaceClass __main__.IOther>, <implementedBy __builtin__.object>)` and of course the bases for `IOther` are just `(<InterfaceClass zope.interface.Interface>,)`. So instead of `Interface` being almost at the very end of the list, it winds up somewhere in the middle. 

Maybe `ro` (or the calculation for `__sro__` in `SpecificationBase.changed`) should take care to put `Interface` at the end (just before `<implementedBy __builtin__.object>`) always? 

With linear inheritance, `Interface` is always at the end:
```pycon
In [100]: @zope.interface.implementer(IFoo)
     ...: class Foo(object): pass
     ...:

In [101]: ro(zope.interface.providedBy(Foo()))
Out[101]:
[<implementedBy __main__.Foo>,
 <InterfaceClass __main__.IFoo>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __builtin__.object>]

In [102]: class Bar(Foo): pass

In [103]: ro(zope.interface.providedBy(Bar()))
Out[103]:
[<implementedBy __main__.Bar>,
 <implementedBy __main__.Foo>,
 <InterfaceClass __main__.IFoo>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __builtin__.object>]

In [104]: class Biz(Bar): pass

In [105]: ro(zope.interface.providedBy(Biz()))
Out[105]:
[<implementedBy __main__.Biz>,
 <implementedBy __main__.Bar>,
 <implementedBy __main__.Foo>,
 <InterfaceClass __main__.IFoo>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __builtin__.object>]
```

Even if you mix in a new interface far down the list:
```pycon
In [106]: @zope.interface.implementer(IOther)
     ...: class Baz(Bar):
     ...:     pass
     ...:

In [107]: ro(zope.interface.providedBy(Baz()))
Out[107]:
[<implementedBy __main__.Baz>,
 <InterfaceClass __main__.IOther>,
 <implementedBy __main__.Bar>,
 <implementedBy __main__.Foo>,
 <InterfaceClass __main__.IFoo>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __builtin__.object>]
```

Adding multiple inheritance and another interface far down the list keeps `Interface` at the end:
```pycon
In [108]: class ISecond(zope.interface.Interface):
     ...:     pass
     ...:

In [109]: @zope.interface.implementer(ISecond)
     ...: class Second(object):
     ...:     pass
     ...:

In [110]: class SecondBaz(Second, Baz):
     ...:     pass
     ...:

In [111]: ro(zope.interface.providedBy(SecondBaz()))
Out[111]:
[<implementedBy __main__.SecondBaz>,
 <implementedBy __main__.Second>,
 <InterfaceClass __main__.ISecond>,
 <implementedBy __main__.Baz>,
 <InterfaceClass __main__.IOther>,
 <implementedBy __main__.Bar>,
 <implementedBy __main__.Foo>,
 <InterfaceClass __main__.IFoo>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __builtin__.object>]

In [112]: class BazSecond(Baz, Second):
     ...:     pass
     ...:

In [113]: ro(zope.interface.providedBy(BazSecond()))
Out[113]:
[<implementedBy __main__.BazSecond>,
 <implementedBy __main__.Baz>,
 <InterfaceClass __main__.IOther>,
 <implementedBy __main__.Bar>,
 <implementedBy __main__.Foo>,
 <InterfaceClass __main__.IFoo>,
 <implementedBy __main__.Second>,
 <InterfaceClass __main__.ISecond>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __builtin__.object>]

In [114]: class ContextBazSecond(Context, Baz, Second):
     ...:     pass
     ...:

In [115]: ro(zope.interface.providedBy(ContextBazSecond()))
Out[115]:
[<implementedBy __main__.ContextBazSecond>,
 <implementedBy __main__.Context>,
 <implementedBy __main__.Baz>,
 <InterfaceClass __main__.IOther>,
 <implementedBy __main__.Bar>,
 <implementedBy __main__.Foo>,
 <InterfaceClass __main__.IFoo>,
 <implementedBy __main__.Second>,
 <InterfaceClass __main__.ISecond>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __builtin__.object>]
```

Here's where things get surprising. If we derive a class from both `Context` and `Far`, `Interface` is still where we expect, just before `object`:

```pycon
In [124]: class ContextBar(Context, Bar):
     ...:     pass
     ...: ro(zope.interface.providedBy(ContextBar()))
     ...:
Out[124]:
[<implementedBy __main__.ContextBar>,
 <implementedBy __main__.Context>,
 <implementedBy __main__.Bar>,
 <implementedBy __main__.Foo>,
 <InterfaceClass __main__.IFoo>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __builtin__.object>]
```

But if we swap the order, `Interface` winds up in front of `Context`, not `object` (because climbing the inheritance order from `Bar` -> `Foo` -> `IFoo` -> `Interface` happens before `Context` -> `object`):

In [125]: class BarContext(Bar, Context):
     ...:     pass
     ...: ro(zope.interface.providedBy(BarContext()))
     ...:
Out[125]:
[<implementedBy __main__.BarContext>,
 <implementedBy __main__.Bar>,
 <implementedBy __main__.Foo>,
 <InterfaceClass __main__.IFoo>,
 <InterfaceClass zope.interface.Interface>,
 <implementedBy __main__.Context>,
 <implementedBy __builtin__.object>]
```

I think this is arguably a bug. In the same way that Python's linearization always puts `object` at the end, I think `ro` should always put `Interface` just before `object`.

Changing that, however, might be a pretty big deal.

**Comment by jamadden** [comment]
The underlying cause, I think, is that we have two root objects with no `__bases__`: `<implementedBy object>` and `Interface`. Thus, when those are mixed together, the RO algorithm is completely agnostic as to how they wind up ordered relative to each other. (It may or may not be relevant that `implementedBy(object).__bases__ == ()`, while `implementedBy(object).__sro__ == (implementedBy(object), Interface)`.)

I can think of a few possible ways to fix this.

One is to just re-order the results of the RO algorithm after its all said and done. We already do something kind of like that just to make sure that `Interface` winds up in all Specifications: that's how it winds up in the `__sro__` for `<implementedBy object>` despite having no bases. We'd just have to make sure and put it in the proper place.

Another would be to *actually* make `Interface` a `__base__` of `implementedBy(object)`. That's nice and symmetric, and the pureist it me really likes it. It has the side effect of making more things appear to directly implement `Interface` though. That can cause problems: this works in current master and released versions:
```pycon
>>> from zope.interface import *
>>> class IFoo(Interface):
...     pass
...
>>> @implementer(IFoo)
... class Foo(object):
...     pass
...
>>> from zope.interface.registry import Components
>>> Components().registerUtility(Foo())
None
```
But if the this change is made, it raises "TypeError: The utility doesn't provide a single interface and no provided interface was specified." I suspect this could be worked around, but it's something of a bigger change.

Last, the RO algorithm itself could be tweaked. In the C3 algorithm, it's easy: if we provide `Interface` as an extra base to consider (`C.__bases__ + (Interface,)`), `Interface` is always going to wind up exactly where it belongs. Where is that? The same place it is in the `__sro__` of `<implementedBy object>`: dead last. All `implementedBy(X)` would end in `(…,<implementedBy builtins.object>, <InterfaceClass zope.interface.Interface>)`. This is a flip flop from how many of them are now. I think it's more consistent, though. I ran the Plone `buildout.coredev` suite with that change, and got no (additional) failures.

Thoughts?
