### ISSUE TITLE
Leak in tests having persistent registries due to caching in zope.interface.registry._UtilityRegistrations

### ISSUE THREAD

**Issue by jimfulton** [zopefoundation/zope.interface#83]
Standard test cleanup doesn't deal with the cache.  It wouldn't be sufficient to simply have zope.interface.registry.Components.__init__ clear it's own cache entry, because there may be entries for persistent registries that need to be dealt with too.

**Comment by jamadden** [comment]
I'm afraid I don't understand what the leak is. If a persistent registry is still in the connection cache, then there's not a leak because it can be used again, it's still accessible. If it is removed from the connection cache, then the weakref will clear and [its cache entry will be removed](https://github.com/zopefoundation/zope.interface/blob/master/src/zope/interface/registry.py#L100).

**Comment by jimfulton** [comment]
It's a leak detected by test runners.

**Comment by jimfulton** [comment]
I'm 99% sure it's not a real leak, but it's still a problem.
